### PR TITLE
🔙 Restore Domain events

### LINKED ISSUE #37: 🔙 Restore Domain Events feature
Keep Domain Events and Application Events separate.

Domain Events are added to the Domain Entities and raised from ApplicationDbContext when changes are saved. The domain events are handled using the MediatR `INotificationHandler`

Application Events can be raised from within the Application Commands/Queries using `mediator.Publish()` and are also handled using the MediatR `INotificationHandler`

This does mean that we will need to pay the price of depending on MediatR in our Domain Layer - but it is a small price to pay.

### PR DESCRIPTION
**Pull request by Hona**
Fixes #37

### CODE REVIEW

**Comment by matt-goldman** [comment]
I'm not sold on this. Domain has an external dependency. I think the result is the same with our previous iteration; I understand that this means that technically, because they are not in the domain, they are not domain events. However, it's a question of compromise, and that's a compromise I prefer to taking an external dependency in Domain.

Is there another way we can design this? So we can keep the _logic_ for the domain events in domain, but have the dependency somewhere else?

**Comment by danielmackay** [comment]
@Hona - have tested this and all works as expected.

@matt-goldman - I understand the concern from a pure domain PoV, but all things considered I am happy with the proposed trade off to add `MediatR` to the domain.

**Review by danielmackay — APPROVED** [review]

**Review by christoment — APPROVED** [review]
Approved - and also as per our discussion, we want to clearly document why we put this back in 😄

**Comment by danielmackay** [comment]
> Approved - and also as per our discussion, we want to clearly document why we put this back in 😄

@christoment - will get done via https://github.com/SSWConsulting/CleanArchitectureV2/issues/50

**Pull request merged**
